namespace csharp_codegen.Generators;

/// <summary>生成される全C#ファイルの先頭に付与するDO NOT EDITコメント。</summary>
public static class GeneratedFileHeader
{
    public const string Text =
        """
        // <auto-generated/>
        // DO NOT EDIT: このファイルは master-data-pipeline によって自動生成されています。
        // 直接編集せず、スプレッドシートまたは schema/ 配下の定義を変更してください。

        """;
}
